theme: jekyll-theme-slate

title: SESAR Documentation
url: https://www.geosamples.org
description: Documentation for SESAR as of January 12, 2020

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

collections: 
  arch_design:
    output: true
    sort_by: title
    order: 
      - overview
  ogc_wxs:
    output: true
  rest_services:
    output: true
  user_communities:
    output: true
  web_services:
    output: false
    sort_by: title
    order: 
      - overview
  release_notes:
    output: true
    sort_by: title
    order: 
      - overview
      
