theme: jekyll-theme-slate
title: Documentation
email: jdf@ldeo.columbia.edu

github_username: geosamples
sesar_login: https://app.geosamples.org
sesar_website: http://www.geosamples.org
sesar_search: http://www-staging.geosamples.org/?s=

# url: ""
baseurl: "sesar-doc" # the subpath of your site, e.g. /blog
description: Documentation for SESAR as of January 12, 2020

logo_desktop: assets/images/sesar_vertical_website_logo_black.png
logo_mobile: assets/images/sesar_website_logo_bnw.png

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

collections: 
  arch_design:
    title: Architecture and Design
    output: true
    sort_by: title
    order: 
      - overview
  web_services:
    title: Web Services
    output: true 
  rest_services:
    title: REST Services
    output: true
      ogc_wxs:
    title: Open Geospatial Consortium (OGC)
    output: true 
  user_communities:
    title: User Communities
    output: true
    sort_by: title
    order: 
      - overview
  # dbdocs:
  #   title: Database Documentation
  #   output: true
  #   sort_by: title

dbdocs: 
  columns:
    title: columns
  foreignKeys:
    title: foreignKeys
  indexes:
    title: indexes
  schemas:
    title: schemas
  tables:
    title: tables
  views:
    title: views
  diagrams:
    title: diagrams    
  procedures:
    title: procedures
  sequences:
    title: sequences
  triggers:
    title: triggers
    
  # release_notes:
  #   title: Release Notes
  #   output: true
  #   sort_by: title
  #   order: 
  #     - overview


funder:
  name: nsf
  logo: assets/images/nsf-all-color.png
  description: Hosted at the Lamont-Doherty Earth Observatory of Columbia University and funded by National Science Foundation
