theme: minima
# theme: jekyll-theme-slate
title: Resources for Developers
subtitle: Documentation
email: jdf@ldeo.columbia.edu

github_username: geosamples
github_repo: geosamples

sesar_team: SESAR team
sesar_login: https://app.geosamples.org
sesar_website: http://www.geosamples.org
sesar_search: http://www-staging.geosamples.org/?s=

url: ""
# baseurl: "sesar-doc" # the subpath of your site, e.g. /blog
description: Documentation for SESAR as of January 12, 2021

logo_desktop: assets/images/sesar_vertical_website_logo_black.png
logo_mobile: assets/images/sesar_website_logo_bnw.png

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

collections: 
  arch_design:
    title: Architecture and Design
    output: true
    sort_by: title
    display_order: 1
    order: 
      - overview.md
  web_services:
    title: Web Services
    output: true
    display_order: 2
  rest_services:
    title: REST Services
    output: true
    display_order: 3
  ogc_wxs:
    title: Open Geospatial Consortium (OGC) Services
    output: true 
    display_order: 4
  user_communities:
    title: Use Cases
    output: true
    sort_by: title
    display_order: 5
    order: 
      - overview.md
  # dbdocs:
  #   title: Database Documentation
  #   output: true
  #   sort_by: title

dbdocs: 
  columns:
    title: columns
  foreignKeys:
    title: foreignKeys
  indexes:
    title: indexes
  schemas:
    title: schemas
  tables:
    title: tables
  views:
    title: views
  diagrams:
    title: diagrams    
  procedures:
    title: procedures
  sequences:
    title: sequences
  triggers:
    title: triggers
    
  # release_notes:
  #   title: Release Notes
  #   output: true
  #   sort_by: title
  #   order: 
  #     - overview


funder:
  name: nsf
  logo: assets/images/nsf-all-color.png
  description: Hosted at the Lamont-Doherty Earth Observatory of Columbia University and funded by the National Science Foundation
