theme: jekyll-theme-slate

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

collections: 
  arch_design:
    output: true
    sort_by: title
    order: 
      - overview
  ogc_wxs:
    output: true
  rest_services:
    output: true
  user_communities:
    output: true
  web_services:
    output: true
    sort_by: title
    order: 
      - overview
  release_notes:
    output: true
    sort_by: title
    order: 
      - overview
      